---
dist: xenial

git:
  quiet: true

language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'
  - nightly

matrix:
  allow_failures:
    - php: nightly

services:
  - mysql

before_install:
  - make database

before_script:
  - composer self-update

script:
  - make phpcs
  - make environment
  - make install
  - make test

after_failure:
  - make logs

